services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
          "-e",
          "SELECT 1",
        ]
      timeout: 20s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: web:latest
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    
    depends_on:
      db:
        condition: service_healthy



volumes:
  mysql_data:

