FROM python:latest

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# RUN apt update && apt install -y bash
# SHELL ["/bin/bash", "-c"]

# RUN pip install uv
# RUN uv venv -v
# RUN source .venv/bin/activate
# ENV PATH="/app/.venv/bin:$PATH"
# RUN which python
# RUN apt update && apt upgrade -y
# RUN apt install pkg-config python3-dev default-libmysqlclient-dev build-essential -y
COPY requirements.txt .
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt 
COPY . /app/


# EXPOSE 8000

# RUN chmod +x /app/django.sh

# ENTRYPOINT ["/app/django.sh"]